(function ( window){
	
	var _data ={
		category:[
			[//2010年
				year:[
					[//捐赠指数
				        {name : 'Afghanistan',value:39, number:38},
					    {name : 'Angola',value:29, number:41},
					    {name : 'Albania',value:112, number:24},
					    {name : 'United Arab Emirates',value:50, number:36},
					    {name : 'Argentina',value:76, number:30},
					    {name : 'Armenia',value:115, number:23},
					    {name : 'French Southern and Antarctic Lands',value:-1, number:-1},
					    {name : 'Australia',value:1, number:57},
					    {name : 'Austria',value:10, number:52},
					    {name : 'Azerbaijan',value:67, number:32},
					    {name : 'Burundi',value:152, number:12},
					    {name : 'Belgium',value:50, number:36},
					    {name : 'Benin',value:106, number:25},
					    {name : 'Burkina Faso',value:112, number:20},
					    {name : 'Bangladesh',value:146, number:15},
					    {name : 'Bulgaria',value:141, number:17},
					    {name : 'The Bahamas',value:-1, number:-1},
					    {name : 'Bosnia and Herzegovina',value:121, number:21},
					    {name : 'Belarus',value:106, number:25},
					    {name : 'Belize',value:59, number:35},
					    {name : 'Bermuda',value:-1, number:-1},
					    {name : 'Bolivia',value:72, number:31},
					    {name : 'Brazil',value:76, number:30},
					    {name : 'Brunei',value:-1, number:-1},
					    {name : 'Bhutan',value:-1, number:-1},
					    {name : 'Botswana',value:67, number:32},
					    {name : 'Central African Republic',value:33, number:40},
					    {name : 'Canada',value:3, number:56},			
					    {name : 'Switzerland',value:5, number:55},
					    {name : 'Chile',value:39, number:38},
					    {name : 'China',value:147, number:14},
					    {name : 'Ivory Coast',value:-1, number:-1},
					    {name : 'Cameroon',value:81, number:29},
					    {name : 'Democratic Republic of the Congo',value:121, number:21},
					    {name : 'Republic of the Congo',value:91, number:27},
					    {name : 'Colombia',value:50, number:36},
					    {name : 'Costa Rica',value:36, number:39},
					    {name : 'Cuba',value:-1, number:-1},
					    {name : 'Northern Cyprus',value:-1, number:-1},
					    {name : 'Cyprus',value:50, number:36},
					    {name : 'Czech Republic',value:81, number:29},
					    {name : 'Germany',value:18, number:44},
					    {name : 'Djibouti',value:86, number:28},
					    {name : 'Denmark',value:18, number:44},
					    {name : 'Dominican Republic',value:62, number:34},
					    {name : 'Algeria',value:106, number:25},
					    {name : 'Ecuador',value:115, number:23},
					    {name : 'Egypt',value:100, number:26},
					    {name : 'Eritrea',value:-1, number:-1},
					    {name : 'Spain',value:91, number:27},			
					    {name : 'Estonia',value:121, number:21},			
					    {name : 'Ethiopia',value:106, number:25},
					    {name : 'Finland',value:45, number:37},
					    {name : 'Fiji',value:-1, number:-1},
					    {name : 'Falkland Islands',value:-1, number:-1},
					    {name : 'France',value:91, number:27},
					    {name : 'Gabon',value:-1, number:-1},
					    {name : 'United Kingdom',value:8, number:53},		
					    {name : 'Georgia',value:134, number:19},
					    {name : 'Ghana',value:45, number:37},
					    {name : 'Guinea',value:18, number:44},
					    {name : 'Gambia',value:-1, number:-1},
					    {name : 'Guinea Bissau',value:-1, number:-1},
					    {name : 'Equatorial Guinea',value:-1, number:-1},
					    {name : 'Greece',value:147, number:14},
					    {name : 'Greenland',value:-1, number:-1},
					    {name : 'Guatemala',value:22, number:43	},		
					    {name : 'French Guiana',value:-1, number:-1},
					    {name : 'Guyana',value:16, number:45},
					    {name : 'Honduras',value:62, number:34},
					    {name : 'Croatia',value:119, number:22},
					    {name : 'Haiti',value:39, number:38},
					    {name : 'Hungary',value:121, number:21},
					    {name : 'Indonesia',value:50, number:36},
					    {name : 'India',value:134, number:19},
					    {name : 'Ireland',value:3, number:56},			
					    {name : 'Iran',value:86, number:28},
					    {name : 'Iraq',value:106, number:25},			
				        {name : 'Iceland',value:14, number:47},
				        {name : 'Israel',value:31, number:41},
				        {name : 'Italy',value:21, number:44},
				        {name : 'Jamaica',value:50, number:36},
				        {name : 'Jordan',value:129, number:20},
				        {name : 'Japan',value:119, number:22},
				        {name : 'Kazakhstan',value:121, number:21},
				        {name : 'Kenya',value:29, number:41},
				        {name : 'Kyrgyzstan',value:121, number:21},
				        {name : 'Cambodia',value:142, number:16},
				        {name : 'South Korea',value:-1, number:-1},
				        {name : 'Kosovo',value:121, number:21},     
				        {name : 'Kuwait',value:25, number:42},
				        {name : 'Laos',value:11, number:50},
				        {name : 'Lebanon',value:45, number:37},
				        {name : 'Liberia',value:39, number:38},
				        {name : 'Libya',value:-1, number:-1},
				        {name : 'Sri Lanka',value:8, number:53},	               
				        {name : 'Lesotho',value:-1, number:-1},
				        {name : 'Lithuania',value:147, number:14},
				        {name : 'Luxembourg',value:25, number:42},
				        {name : 'Latvia',value:115, number:23},
				        {name : 'Morocco',value:33, number:40},
				        {name : 'Moldova',value:100, number:26},
				        {name : 'Madagascar',value:1152, number:12},
				        {name : 'Mexico',value:67, number:32},
				        {name : 'Macedonia',value:91, number:27},
				        {name : 'Mali',value:91, number:27},
				        {name : 'Myanmar',value:22, number:43},               
				        {name : 'Montenegro',value:138, number:18},
				        {name : 'Mongolia',value:67, number:32},
				        {name : 'Mozambique',value:129, number:20},
				        {name : 'Mauritania',value:67, number:32},
				        {name : 'Malawi',value:29, number:41},
				        {name : 'Malaysia',value:76, number:30},
				        {name : 'Namibia',value:86, number:28},
				        {name : 'New Caledonia',value:-1, number:-1},
				        {name : 'Niger',value:100, number:26},
				        {name : 'Nigeria',value:36, number:39},	                
				        {name : 'Nicaragua',value:76, number:30},
				        {name : 'Netherlands',value:7, number:54},	               
				        {name : 'Norway',value:25, number:42},
				        {name : 'Nepal',value:100, number:26},
				        {name : 'New Zealand',value:1, number:57},              
				        {name : 'Oman',value:-1, number:-1},
				        {name : 'Pakistan',value:142, number:16},
				        {name : 'Panama',value:66, number:33},
				        {name : 'Peru',value:91, number:27},
				        {name : 'Philippines',value:50, number:36},	               
				        {name : 'Papua New Guinea',value:-1, number:-1},
				        {name : 'Poland',value:81, number:29},
				        {name : 'Puerto Rico',value:62, number:34},
				        {name : 'North Korea',value:-1, number:-1},  
				        {name : 'Portugal',value:129, number:20},
				        {name : 'Paraguay',value:106, number:25},
				        {name : 'Qatar',value:16, number:45},	                
				        {name : 'Romania',value:142, number:16},
				        {name : 'Russia',value:138, number:18},
				        {name : 'Rwanda',value:142, number:16},
				        {name : 'Western Sahara',value:-1, number:-1},
				        {name : 'Saudi Arabia',value:86, number:28},
				        {name : 'Sudan',value:39, number:38},
				        {name : 'South Sudan',value:-1, number:-1},
				        {name : 'Senegal',value:91, number:27},              
				        {name : 'Solomon Islands',value:-1, number:-1},
				        {name : 'Sierra Leone',value:11, number:50},
				        {name : 'El Salvador',value:115, number:23},
				        {name : 'Somaliland',value:39, number:38},
				        {name : 'Somalia',value:-1, number:-1},
				        {name : 'Republic of Serbia',value:150, number:13},
				        {name : 'Suriname',value:-1, number:-1},    
				        {name : 'Slovakia',value:112, number:24},
				        {name : 'Slovenia',value:62, number:34},
				        {name : 'Sweden',value:45, number:37},
				        {name : 'Swaziland',value:-1, number:-1},
				        {name : 'Syria',value:59, number:35},	                
				        {name : 'Chad',value:81, number:29},
				        {name : 'Togo',value:129, number:20},
				        {name : 'Thailand',value:25, number:42},
				        {name : 'Tajikistan',value:50, number:36},
				        {name : 'Turkmenistan',value:14, number:47},	               
				        {name : 'East Timor',value:-1, number:-1},
				        {name : 'Trinidad and Tobago',value:22, number:43},
				        {name : 'Tunisia',value:72, number:31},
				        {name : 'Turkey',value:134, number:19},
				        {name : 'United Republic of Tanzania',value:33, number:40},
				        {name : 'Uganda',value:72, number:31},
				        {name : 'Ukraine',value:150, number:13},
				        {name : 'Uruguay',value:100, number:26},
				        {name : 'United States of America',value:5, number:55},        
				        {name : 'Uzbekistan',value:59, number:35},
				        {name : 'Venezuela',value:115, number:24},
				        {name : 'Vietnam',value:138, number:18},
				        {name : 'Vanuatu',value:-1, number:-1},
				        {name : 'West Bank',value:-1, number:-1},
				        {name : 'Yemen',value:100, number:26},
				        {name : 'South Africa',value:76, number:30},
				        {name : 'Zambia',value:45, number:37},
				        {name : 'Zimbabwe',value:91, number:27}
				    ],
				    [ //帮助陌生人指数
						{name : 'Afghanistan', value:36,number:55},	
						{name : 'Angola', value:15,number:61},
						{name : 'Albania', value:130,number:31},
						{name : 'United Arab Emirates', value:-1,number:-1},
						{name : 'Argentina', value:45,number:52},
						{name : 'Armenia', value:50,number:51},
						{name : 'French Southern and Antarctic Lands', value:-1,number:-1},
						{name : 'Australia', value:8,number:64},
						{name : 'Austria', value:26,number:58},
						{name : 'Azerbaijan', value:65,number:48},
						{name : 'Burundi', value:146,number:21},
						{name : 'Belgium', value:74,number:51},
						{name : 'Benin', value:103,number:37},
						{name : 'Burkina Faso', value:90,number:41},
						{name : 'Bangladesh', value:137,number:29},
						{name : 'Bulgaria', value:134,number:30},
						{name : 'The Bahamas', value:-1,number:-1},
						{name : 'Bosnia and Herzegovina', value:-1,number:-1},
						{name : 'Belarus', value:125,number:32},
						{name : 'Belize', value:55,number:50},
						{name : 'Bermuda', value:-1,number:-1},
						{name : 'Bolivia', value:55,number:50},
						{name : 'Brazil', value:61,number:49},
						{name : 'Brunei', value:-1,number:-1},
						{name : 'Bhutan', value:-1,number:-1},
						{name : 'Botswana', value:12,number:62},
						{name : 'Central African Republic', value:-1,number:-1},
						{name : 'Canada', value:4,number:68},
						{name : 'Switzerland', value:21,number:60},
						{name : 'Chile', value:61,number:49},
						{name : 'China', value:140,number:28},
						{name : 'Ivory Coast', value:-1,number:-1},
						{name : 'Cameroon', value:33,number:56},
						{name : 'Democratic Republic of the Congo', value:125,number:32},
						{name : 'Republic of the Congo', value:-1,number:-1},
						{name : 'Colombia', value:10,number:63},
						{name : 'Costa Rica', value:36,number:55},
						{name : 'Cuba', value:-1,number:-1},
						{name : 'Northern Cyprus', value:-1,number:-1},
						{name : 'Cyprus', value:74,number:45},
						{name : 'Czech Republic', value:103,number:37},
						{name : 'Germany', value:33,number:56},
						{name : 'Djibouti', value:61,number:49},
						{name : 'Denmark', value:74,number:45},
						{name : 'Dominican Republic', value:45,number:52},
						{name : 'Algeria', value:55,number:50},
						{name : 'Ecuador', value:110,number:35},
						{name : 'Egypt', value:45,number:52},
						{name : 'Eritrea', value:-1,number:-1},
						{name : 'Spain', value:81,number:44},
						{name : 'Estonia', value:103,number:37},
						{name : 'Ethiopia', value:99,number:38},
						{name : 'Finland', value:86,number:42},	
						{name : 'Fiji', value:-1,number:-1},
						{name : 'Falkland Islands', value:-1,number:-1},
						{name : 'France', value:140,number:28},
						{name : 'Gabon', value:-1,number:-1},
						{name : 'United Kingdom',value:26,number:58},
						{name : 'Georgia', value:103,number:37},
						{name : 'Ghana', value:29,number:27},
						{name : 'Guinea', value:15,number:61},
						{name : 'Gambia', value:-1,number:-1},
						{name : 'Guinea Bissau', value:-1,number:-1},
						{name : 'Equatorial Guinea', value:-1,number:-1},
						{name : 'Greece', value:140,number:28},
						{name : 'Greenland', value:-1,number:-1},
						{name : 'Guatemala', value:50,number:51},
						{name : 'French Guiana', value:-1,number:-1},
						{name : 'Guyana', value:5,number:67},
						{name : 'Honduras', value:90,number:41},
						{name : 'Croatia', value:117,number:34},
						{name : 'Haiti', value:110,number:35},
						{name : 'Hungary', value:125,number:32},
						{name : 'Indonesia', value:110,number:35},
						{name : 'India',value:134,number:34},
						{name : 'Ireland',value:21,number:60},
						{name : 'Iran', value:99,number:38},
						{name : 'Iraq', value:15,number:61},			
						{name : 'Iceland', value:70,number:47},
						{name : 'Israel', value:70,number:47},
						{name : 'Italy', value:74,number:45},
						{name : 'Jamaica', value:15,number:61},
						{name : 'Jordan', value:121,number:33},
						{name : 'Japan', value:145,number:25},
						{name : 'Kazakhstan', value:117,number:34},         
						{name : 'Kenya', value:8,number:64},              
						{name : 'Kyrgyzstan', value:130,number:31},             
						{name : 'Cambodia', value:153,number:13},           
						{name : 'South Korea', value:99,number:38},          
						{name : 'Kosovo', value:149,number:20},    
						{name : 'Kuwait', value:5,number:67},        
						{name : 'Laos', value:41,number:53},             
						{name : 'Lebanon', value:29,number:57},            
						{name : 'Liberia', value:1,number:76},              
						{name : 'Libya', value:-1,number:-1},            
						{name : 'Sri Lanka', value:55,number:50},        
						{name : 'Lesotho', value:-1,number:-1},        
						{name : 'Lithuania', value:121,number:33},     
						{name : 'Luxembourg', value:90,number:41},     
						{name : 'Latvia', value:117,number:34},               
						{name : 'Morocco', value:81,number:44},              
						{name : 'Moldova', value:86,number:42},               
						{name : 'Madagascar', value:152,number:18},               
						{name : 'Mexico', value:55,number:50},               
						{name : 'Macedonia', value:117,number:34},                
						{name : 'Mali', value:33,number:56},               
						{name : 'Myanmar',value:45,number:52},            
						{name : 'Montenegro', value:130,number:31},         
						{name : 'Mongolia', value:125,number:32},              
						{name : 'Mauritania', value:36,number:55},            
						{name : 'Malawi', value:26,number:58},             
						{name : 'Malaysia', value:134,number:30},          
						{name : 'Namibia', value:61,number:49},            
						{name : 'New Caledonia', value:-1,number:-1},     
						{name : 'Niger', value:15,number:61},     
						{name : 'Nigeria', value:15,number:61},   
						{name : 'Nicaragua', value:97,number:39},                
						{name : 'Netherlands',value:73,number:46},             
						{name : 'Norway', value:74,number:45},             
						{name : 'Nepal', value:108,number:36},               
						{name : 'New Zealand', value:10,number:63},              
						{name : 'Oman', value:-1,number:-1},              
						{name : 'Pakistan', value:149,number:20},             
						{name : 'Panama', value:84,number:43},               
						{name : 'Peru', value:86,number:42},               
						{name : 'Philippines', value:65,number:48},       
						{name : 'Papua New Guinea', value:-1,number:-1},     
						{name : 'Poland', value:110,number:35},          
						{name : 'Puerto Rico', value:36,number:55},   
						{name : 'North Korea', value:-1,number:-1},  
						{name : 'Portugal', value:121,number:33},           
						{name : 'Paraguay', value:140,number:28},           
						{name : 'Qatar', value:41,number:53},               
						{name : 'Romania', value:140,number:28},              
						{name : 'Russia', value:137,number:29},             
						{name : 'Rwanda', value:146,number:21},
						{name : 'Western Sahara', value:-1,number:-1},            
						{name : 'Saudi Arabia', value:74,number:45},              
						{name : 'Sudan', value:3,number:69},              
						{name : 'South Sudan', value:-1,number:-1},         
						{name : 'Senegal', value:45,number:52},      
						{name : 'Solomon Islands', value:-1,number:-1},         
						{name : 'Sierra Leone', value:2,number:75},       
						{name : 'El Salvador', value:86,number:42},    
						{name : 'Somaliland', value:33,number:56},                
						{name : 'Somalia', value:-1,number:-1},               
						{name : 'Republic of Serbia', value:-1,number:-1},             
						{name : 'Suriname', value:-1,number:-1},               
						{name : 'Slovakia', value:130,number:31},
						{name : 'Slovenia', value:95,number:40},             
						{name : 'Sweden', value:70,number:47},              
						{name : 'Swaziland', value:-1,number:-1},               
						{name : 'Syria', value:12,number:62},               
						{name : 'Chad', value:99,number:38},                
						{name : 'Togo', value:121,number:33},                
						{name : 'Thailand', value:108,number:36},               
						{name : 'Tajikistan', value:65,number:48},              
						{name : 'Turkmenistan', value:12,number:62},               
						{name : 'East Timor', value:-1,number:-1},              
						{name : 'Trinidad and Tobago', value:21,number:60},     
						{name : 'Tunisia', value:15,number:61},           
						{name : 'Turkey', value:110,number:35},          
						{name : 'United Republic of Tanzania', value:-1,number:-1},           
						{name : 'Uganda', value:24,number:59},             
						{name : 'Ukraine', value:151,number:19},           
						{name : 'Uruguay', value:84,number:43},            
						{name : 'United States of America', value:7,number:65},      
						{name : 'Uzbekistan', value:90,number:41},                
						{name : 'Venezuela', value:103,number:37},                
						{name : 'Vietnam', value:125,number:32},             
						{name : 'Vanuatu', value:-1,number:-1},          
						{name : 'West Bank', value:-1,number:-1},               
						{name : 'Yemen', value:41,number:53},             
						{name : 'South Africa', value:29,number:57},            
						{name : 'Zambia', value:24,number:59},            
						{name : 'Zimbabwe', value:41,number:53}
					],
					[ // 资金援助指数
				        {name : 'Afghanistan',value:75,number:17},
					    {name : 'Angola',value:-1,number:-1},
					    {name : 'Albania',value:107,number:10},
					    {name : 'United Arab Emirates',value:-1,number:-1},
					    {name : 'Argentina',value:75,number:17},
					    {name : 'Armenia',value:113,number:8},
					    {name : 'French Southern and Antarctic Lands',value:-1,number:-1},
					    {name : 'Australia',value:18,number:34},
					    {name : 'Austria',value:-1,number:-1},
					    {name : 'Azerbaijan',value:30,number:28},
					    {name : 'Burundi',value:-1,number:-1},
					    {name : 'Belgium',value:41,number:25},
					    {name : 'Benin',value:95,number:12},
					    {name : 'Burkina Faso',value:113,number:8},
					    {name : 'Bangladesh',value:90,number:13},
					    {name : 'Bulgaria',value:121,number:7},
					    {name : 'The Bahamas',value:-1,number:-1},
					    {name : 'Bosnia and Herzegovina',value:-1,number:-1},
					    {name : 'Belarus',value:22,number:30},
					    {name : 'Belize',value:-1,number:-1},
					    {name : 'Bermuda',value:-1,number:-1},
					    {name : 'Bolivia',value:47,number:24},
					    {name : 'Brazil',value:90,number:13},
					    {name : 'Brunei',value:-1,number:-1},
					    {name : 'Bhutan',value:-1,number:-1},
					    {name : 'Botswana',value:60,number:19},
					    {name : 'Central African Republic',value:-1,number:-1},
					    {name : 'Canada',value:6,number:42},
					    {name : 'Switzerland',value:20,number:32},
					    {name : 'Chile',value:90,number:13},
					    {name : 'China',value:131,number:4},
					    {name : 'Ivory Coast',value:-1,number:-1},
					    {name : 'Cameroon',value:1,number:35},
					    {name : 'Democratic Republic of the Congo',value:-1,number:-1},
					    {name : 'Republic of the Congo',value:-1,number:-1},
					    {name : 'Colombia',value:47,number:24},
					    {name : 'Costa Rica',value:34,number:27},
					    {name : 'Cuba',value:-1,number:-1},
					    {name : 'Northern Cyprus',value:-1,number:-1},
					    {name : 'Cyprus',value:34,number:27},
					    {name : 'Czech Republic',value:88,number:14},
					    {name : 'Germany',value:34,number:27},
					    {name : 'Djibouti',value:-1,number:-1},
					    {name : 'Denmark',value:57,number:20},
					    {name : 'Dominican Republic',value:16,number:35},
					    {name : 'Algeria',value:113,number:8},
					    {name : 'Ecuador',value:82,number:15},
					    {name : 'Egypt',value:121,number:7},
					    {name : 'Eritrea',value:-1,number:-1},
					    {name : 'Spain',value:1,number:35},
					    {name : 'Estonia',value:75,number:17},
					    {name : 'Ethiopia',value:102,number:11},
					    {name : 'Finland',value:34,number:27},
					    {name : 'Fiji',value:-1,number:-1},
					    {name : 'Falkland Islands',value:-1,number:-1},
					    {name : 'France',value:41,number:25},
					    {name : 'Gabon',value:95,number:12},
					    {name : 'United Kingdom',value:26,number:29},
					    {name : 'Georgia',value:68,number:18},
					    {name : 'Ghana',value:54,number:21},
					    {name : 'Guinea',value:68,number:18},
					    {name : 'Gambia',value:-1,number:-1},
					    {name : 'Guinea Bissau',value:-1,number:-1},
					    {name : 'Equatorial Guinea',value:-1,number:-1},
					    {name : 'Greece',value:131,number:4},
					    {name : 'Greenland',value:-1,number:-1},
					    {name : 'Guatemala',value:8,number:40},
					    {name : 'French Guiana',value:-1,number:-1},
					    {name : 'Guyana',value:-1,number:-1},
					    {name : 'Honduras',value:30,number:28},
					    {name : 'Croatia',value:127,number:6},
					    {name : 'Haiti',value:14,number:36},
					    {name : 'Hungary',value:107,number:10},
					    {name : 'Indonesia',value:22,number:30},
					    {name : 'India',value:68,number:18},
					    {name : 'Ireland',value:11,number:37},
					    {name : 'Iran',value:-1,number:-1},
					    {name : 'Iraq',value:90,number:13},				
				        {name : 'Iceland',value:41,number:25},
				        {name : 'Israel',value:54,number:21},
				        {name : 'Italy',value:41,number:25},
				        {name : 'Jamaica',value:-1,number:-1},
				        {name : 'Jordan',value:-1,number:-1},
				        {name : 'Japan',value:-1,number:-1},
				        {name : 'Kazakhstan',value:26,number:29},
				        {name : 'Kenya',value:-1,number:-1},
				        {name : 'Kyrgyzstan',value:41,number:25},
				        {name : 'Cambodia',value:111,number:9},
				        {name : 'South Korea',value:-1,number:-1},
				        {name : 'Kosovo',value:41,number:25},     
				        {name : 'Kuwait',value:-1,number:-1},
				        {name : 'Laos',value:-1,number:-1},
				        {name : 'Lebanon',value:113,number:8},
				        {name : 'Liberia',value:-1,number:-1},
				        {name : 'Libya',value:-1,number:-1},
				        {name : 'Sri Lanka',value:2,number:26},
				        {name : 'Lesotho',value:-1,number:-1},
				        {name : 'Lithuania',value:95,number:12},
				        {name : 'Luxembourg',value:22,number:30},
				        {name : 'Latvia',value:111,number:9},
				        {name : 'Morocco',value:121,number:7},
				        {name : 'Moldova',value:60,number:19},
				        {name : 'Madagascar',value:34,number:27},
				        {name : 'Mexico',value:-1,number:-1},
				        {name : 'Macedonia',value:121,number:7},
				        {name : 'Mali',value:127,number:6},
				        {name : 'Myanmar',value:4,number:43},
				        {name : 'Montenegro',value:113,number:8},
				        {name : 'Mongolia',value:26,number:29},
				        {name : 'Mozambique',value:-1,number:-1},
				        {name : 'Mauritania',value:95,number:12},
				        {name : 'Malawi',value:22,number:30},
				        {name : 'Malaysia',value:60,number:19},
				        {name : 'Namibia',value:-1,number:-1},
				        {name : 'New Caledonia',value:-1,number:-1},
				        {name : 'Niger',value:102,number:11},
				        {name : 'Nigeria',value:14,number:36},
				        {name : 'Nicaragua',value:75,number:17},
				        {name : 'Netherlands',value:11,number:37},
				        {name : 'Norway',value:16,number:35},
				        {name : 'Nepal',value:40,number:26},
				        {name : 'New Zealand',value:8,number:40},
				        {name : 'Oman',value:-1,number:-1},
				        {name : 'Pakistan',value:82,number:15},
				        {name : 'Panama',value:21,number:31},
				        {name : 'Peru',value:57,number:20},
				        {name : 'Philippines',value:4,number:43},
				        {name : 'Papua New Guinea',value:-1,number:-1},
				        {name : 'Poland',value:95,number:12},
				        {name : 'Puerto Rico',value:-1,number:-1},
				        {name : 'North Korea',value:-1,number:-1},   
				        {name : 'Portugal',value:81,number:16},
				        {name : 'Paraguay',value:47,number:24},
				        {name : 'Qatar',value:60,number:19},
				        {name : 'Romania',value:113,number:8},
				        {name : 'Russia',value:-1,number:-1},
				        {name : 'Rwanda',value:107,number:10},
				        {name : 'Western Sahara',value:-1,number:-1},
				        {name : 'Saudi Arabia',value:88,number:14},
				        {name : 'Sudan',value:60,number:19},
				        {name : 'South Sudan',value:-1,number:-1},
				        {name : 'Senegal',value:82,number:15},
				        {name : 'Solomon Islands',value:-1,number:-1},
				        {name : 'Sierra Leone',value:-1,number:-1},
				        {name : 'El Salvador',value:68,number:18},
				        {name : 'Somaliland',value:68,number:18},
				        {name : 'Somalia',value:-1,number:-1},
				        {name : 'Republic of Serbia',value:121,number:7},
				        {name : 'Suriname',value:53,number:22},                
				        {name : 'Slovakia',value:102,number:11},
				        {name : 'Slovenia',value:18,number:34},
				        {name : 'Sweden',value:90,number:13},
				        {name : 'Swaziland',value:-1,number:-1},
				        {name : 'Syria',value:82,number:15},
				        {name : 'Chad',value:95,number:12},
				        {name : 'Togo',value:-1,number:-1},
				        {name : 'Thailand',value:95,number:12},
				        {name : 'Tajikistan',value:7,number:41},
				        {name : 'Turkmenistan',value:1,number:57},
				        {name : 'East Timor',value:-1,number:-1},
				        {name : 'Trinidad and Tobago',value:-1,number:-1},
				        {name : 'Tunisia',value:131,number:4},
				        {name : 'Turkey',value:130,number:5},
				        {name : 'United Republic of Tanzania',value:60,number:19},
				        {name : 'Uganda',value:51,number:23},
				        {name : 'Ukraine',value:26,number:29},
				        {name : 'Uruguay',value:82,number:15},
				        {name : 'United States of America',value:3,number:45},
				        {name : 'Uzbekistan',value:10,number:38},
				        {name : 'Venezuela',value:60,number:19},
				        {name : 'Vietnam',value:113,number:8},
				        {name : 'Vanuatu',value:-1,number:-1},
				        {name : 'West Bank',value:-1,number:-1},                
				        {name : 'Yemen',value:131,number:4},
				        {name : 'South Africa',value:54,number:21},
				        {name : 'Zambia',value:34,number:27},
				        {name : 'Zimbabwe',value:51,number:23}
				    ],
				    [//志愿服务指数
						{name : 'Afghanistan',value:49, number:23},
						{name : 'Angola',value:9, number:39},
						{name : 'Albania',value:95, number:15},
						{name : 'United Arab Emirates',value:-1, number:-1},
						{name : 'Argentina',value:90, number:16},
						{name : 'Armenia',value:113, number:12},
						{name : 'French Southern and Antarctic Lands',value:-1, number:-1},
						{name : 'Australia',value:13, number:38},
						{name : 'Austria',value:27, number:30},
						{name : 'Azerbaijan',value:36, number:27},
						{name : 'Burundi',value:134, number:7},
						{name : 'Belgium',value:48, number:24},
						{name : 'Benin',value:71, number:19},
						{name : 'Burkina Faso',value:103, number:14},
						{name : 'Bangladesh',value:144, number:5},
						{name : 'Bulgaria',value:152, number:3},
						{name : 'The Bahamas',value:-1, number:-1},
						{name : 'Bosnia and Herzegovina',value:-1, number:-1},
						{name : 'Belarus',value:23, number:32},
						{name : 'Belize',value:36, number:27},
						{name : 'Bermuda',value:-1, number:-1},
						{name : 'Bolivia',value:63, number:20},
						{name : 'Brazil',value:95, number:15},
						{name : 'Brunei',value:-1, number:-1},
						{name : 'Bhutan',value:-1, number:-1},
						{name : 'Botswana',value:71, number:19},
						{name : 'Central African Republic',value:-1, number:-1},
						{name : 'Canada',value:17, number:35},			    
						{name : 'Switzerland',value:20, number:34},
						{name : 'Chile',value:90, number:16},
						{name : 'China',value:148, number:4},
						{name : 'Ivory Coast',value:-1, number:-1},
						{name : 'Cameroon',value:113, number:12},
						{name : 'Democratic Republic of the Congo',value:78, number:18},
						{name : 'Republic of the Congo',value:-1, number:-1},
						{name : 'Colombia',value:63, number:20},
						{name : 'Costa Rica',value:49, number:23},
						{name : 'Cuba',value:-1, number:-1},
						{name : 'Northern Cyprus',value:-1, number:-1},
						{name : 'Cyprus',value:53, number:22},
						{name : 'Czech Republic',value:78, number:18},
						{name : 'Germany',value:31, number:28},
						{name : 'Djibouti',value:90, number:16},
						{name : 'Denmark',value:63, number:20},
						{name : 'Dominican Republic',value:45, number:25},
						{name : 'Algeria',value:127, number:9},
						{name : 'Ecuador',value:90, number:16},
						{name : 'Egypt',value:138, number:6},
						{name : 'Eritrea',value:-1, number:-1},
						{name : 'Spain',value:107, number:13},				    
						{name : 'Estonia',value:95, number:15},			    
						{name : 'Ethiopia',value:107, number:13},
						{name : 'Finland',value:31, number:28},
						{name : 'Fiji',value:-1, number:-1},
						{name : 'Falkland Islands',value:-1, number:-1},
						{name : 'France',value:53, number:22},
						{name : 'Gabon',value:-1, number:-1},
						{name : 'United Kingdom',value:29, number:29},		    
						{name : 'Georgia',value:95, number:15},
						{name : 'Ghana',value:25, number:31},
						{name : 'Guinea',value:5, number:42},
						{name : 'Gambia',value:-1, number:-1},
						{name : 'Guinea Bissau',value:-1, number:-1},
						{name : 'Equatorial Guinea',value:-1, number:-1},
						{name : 'Greece',value:144, number:5},
						{name : 'Greenland',value:-1, number:-1},
						{name : 'Guatemala',value:21, number:33},			    
						{name : 'French Guiana',value:-1, number:-1},
						{name : 'Guyana',value:21, number:33},
						{name : 'Honduras',value:36, number:27},
						{name : 'Croatia',value:138, number:6},
						{name : 'Haiti',value:13, number:38},
						{name : 'Hungary',value:127, number:9},
						{name : 'Indonesia',value:36, number:27},
						{name : 'India',value:113, number:12},
						{name : 'Ireland',value:17, number:35},				    
						{name : 'Iran',value:113, number:12},
						{name : 'Iraq',value:138, number:6},			
						{name : 'Iceland',value:43, number:26},
						{name : 'Israel',value:78, number:18},
						{name : 'Italy',value:90, number:16},
						{name : 'Jamaica',value:78, number:18},
						{name : 'Jordan',value:148, number:4},
						{name : 'Japan',value:49, number:23},
						{name : 'Kazakhstan',value:53, number:22},
						{name : 'Kenya',value:31, number:28},
						{name : 'Kyrgyzstan',value:45, number:25},
						{name : 'Cambodia',value:153, number:2},
						{name : 'South Korea',value:-1, number:-1},
						{name : 'Kosovo',value:127, number:9},     
						{name : 'Kuwait',value:71, number:19},
						{name : 'Laos',value:23, number:32},
						{name : 'Lebanon',value:107, number:13},
						{name : 'Liberia',value:27, number:30},
						{name : 'Libya',value:-1, number:-1},
						{name : 'Sri Lanka',value:2, number:52},	                
						{name : 'Lesotho',value:-1, number:-1},
						{name : 'Lithuania',value:138, number:6},
						{name : 'Luxembourg',value:31, number:28},
						{name : 'Latvia',value:78, number:18},
						{name : 'Morocco',value:148, number:4},
						{name : 'Moldova',value:63, number:20},
						{name : 'Madagascar',value:121, number:11},
						{name : 'Mexico',value:63, number:20},
						{name : 'Macedonia',value:127, number:9},
						{name : 'Mali',value:49, number:23},
						{name : 'Myanmar',value:8, number:40},               
						{name : 'Montenegro',value:138, number:6},
						{name : 'Mongolia',value:25, number:31},
						{name : 'Mozambique',value:103, number:14},
						{name : 'Mauritania',value:95, number:15},
						{name : 'Malawi',value:17, number:35},
						{name : 'Malaysia',value:29, number:29},
						{name : 'Namibia',value:88, number:17},
						{name : 'New Caledonia',value:-1, number:-1},
						{name : 'Niger',value:31, number:28},
						{name : 'Nigeria',value:31, number:28},	                
						{name : 'Nicaragua',value:63, number:20},
						{name : 'Netherlands',value:9, number:39},	                
						{name : 'Norway',value:13, number:38},
						{name : 'Nepal',value:58, number:21},
						{name : 'New Zealand',value:7, number:41},              
						{name : 'Oman',value:-1, number:-1},
						{name : 'Pakistan',value:133, number:8},
						{name : 'Panama',value:58, number:21},
						{name : 'Peru',value:71, number:19},
						{name : 'Philippines',value:16, number:36},	                
						{name : 'Papua New Guinea',value:-1, number:-1},
						{name : 'Poland',value:127, number:9},
						{name : 'Puerto Rico',value:78, number:18},
						{name : 'North Korea',value:-1, number:-1},  
						{name : 'Portugal',value:121, number:11},
						{name : 'Paraguay',value:88, number:17},
						{name : 'Qatar',value:78, number:18},	                
						{name : 'Romania',value:144, number:5},
						{name : 'Russia',value:63, number:20},
						{name : 'Rwanda',value:121, number:11},
						{name : 'Western Sahara',value:-1, number:-1},
						{name : 'Saudi Arabia',value:113, number:12},
						{name : 'Sudan',value:63, number:20},
						{name : 'South Sudan',value:-1, number:-1},
						{name : 'Senegal',value:107, number:13},              
						{name : 'Solomon Islands',value:-1, number:-1},
						{name : 'Sierra Leone',value:4, number:45},
						{name : 'El Salvador',value:113, number:12},
						{name : 'Somaliland',value:49, number:23},
						{name : 'Somalia',value:-1, number:-1},
						{name : 'Republic of Serbia',value:-1, number:-1},
						{name : 'Suriname',value:-1, number:-1},    
						{name : 'Slovakia',value:107, number:13},
						{name : 'Slovenia',value:36, number:27},
						{name : 'Sweden',value:113, number:12},
						{name : 'Swaziland',value:-1, number:-1},
						{name : 'Syria',value:127, number:9},	                
						{name : 'Chad',value:36, number:27},
						{name : 'Togo',value:71, number:19},
						{name : 'Thailand',value:78, number:18},
						{name : 'Tajikistan',value:5, number:42},
						{name : 'Turkmenistan',value:1, number:61},	                
						{name : 'East Timor',value:-1, number:-1},
						{name : 'Trinidad and Tobago',value:45, number:25},
						{name : 'Tunisia',value:113, number:12},
						{name : 'Turkey',value:134, number:7},
						{name : 'United Republic of Tanzania',value:-1, number:-1},
						{name : 'Uganda',value:53, number:22},
						{name : 'Ukraine',value:103, number:14},
						{name : 'Uruguay',value:95, number:15},
						{name : 'United States of America',value:9, number:39},              
						{name : 'Uzbekistan',value:9, number:39},
						{name : 'Venezuela',value:95, number:15},
						{name : 'Vietnam',value:138, number:6},
						{name : 'Vanuatu',value:-1, number:-1},
						{name : 'West Bank',value:-1, number:-1},
						{name : 'Yemen',value:134, number:7},
						{name : 'South Africa',value:71, number:19},
						{name : 'Zambia',value:36, number:27},
						{name : 'Zimbabwe',value:71, number:19}
					]
				]
			],
			[//2013年
				year:[
					[ //捐赠指数
		                {name : 'Afghanistan',value:35, number:40},
					    {name : 'Angola',value:-1, number:-1},
					    {name : 'Albania',value:132, number:160},
					    {name : 'United Arab Emirates',value:-1, number:-1},
					    {name : 'Argentina',value:78, number:28},
					    {name : 'Armenia',value:113, number:21},
					    {name : 'French Southern and Antarctic Lands',value:-1, number:-1},
					    {name : 'Australia',value:7, number:55},
					    {name : 'Austria',value:-1, number:-1},
					    {name : 'Azerbaijan',value:69, number:30},
					    {name : 'Burundi',value:-1, number:-1},
					    {name : 'Belgium',value:57, number:33},
					    {name : 'Benin',value:120, number:19},
					    {name : 'Burkina Faso',value:109, number:21},
					    {name : 'Bangladesh',value:89, number:26},
					    {name : 'Bulgaria',value:118, number:19},
					    {name : 'The Bahamas',value:-1, number:-1},
					    {name : 'Bosnia and Herzegovina',value:-1, number:-1},
					    {name : 'Belarus',value:93, number:25},
					    {name : 'Belize',value:-1, number:-1},
					    {name : 'Bermuda',value:-1, number:-1},
					    {name : 'Bolivia',value:54, number:34},
					    {name : 'Brazil',value:91, number:26},
					    {name : 'Brunei',value:-1, number:-1},
					    {name : 'Bhutan',value:-1, number:-1},
					    {name : 'Botswana',value:84, number:27},
					    {name : 'Central African Republic',value:-1, number:-1},
					    {name : 'Canada',value:2, number:58},			    
					    {name : 'Switzerland',value:12, number:47},
					    {name : 'Chile',value:35, number:40},
					    {name : 'China',value:133, number:16},
					    {name : 'Ivory Coast',value:-1, number:-1},
					    {name : 'Cameroon',value:35, number:61},
					    {name : 'Democratic Republic of the Congo',value:-1, number:-1},
					    {name : 'Republic of the Congo',value:-1, number:-1},
					    {name : 'Colombia',value:31, number:41},
					    {name : 'Costa Rica',value:23, number:43},
					    {name : 'Cuba',value:-1, number:-1},
					    {name : 'Northern Cyprus',value:-1, number:-1},
					    {name : 'Cyprus',value:24, number:43},
					    {name : 'Czech Republic',value:103, number:23},
					    {name : 'Germany',value:22, number:43},
					    {name : 'Djibouti',value:-1, number:-1},
					    {name : 'Denmark',value:25, number:42},
					    {name : 'Dominican Republic',value:39, number:39},
					    {name : 'Algeria',value:109, number:21},
					    {name : 'Ecuador',value:84, number:27},
					    {name : 'Egypt',value:105, number:23},
					    {name : 'Eritrea',value:-1, number:-1},
					    {name : 'Spain',value:57, number:33},				    
					    {name : 'Estonia',value:35, number:61},			    
					    {name : 'Ethiopia',value:109, number:21},
					    {name : 'Finland',value:33, number:40},
					    {name : 'Fiji',value:-1, number:-1},
					    {name : 'Falkland Islands',value:-1, number:-1},
					    {name : 'France',value:77, number:28},
					    {name : 'Gabon',value:78, number:28},
					    {name : 'United Kingdom',value:6, number:57},		    
					    {name : 'Georgia',value:116, number:20},
					    {name : 'Ghana',value:61, number:33},
					    {name : 'Guinea',value:74, number:29},
					    {name : 'Gambia',value:-1, number:-1},
					    {name : 'Guinea Bissau',value:-1, number:-1},
					    {name : 'Equatorial Guinea',value:-1, number:-1},
					    {name : 'Greece',value:135, number:13},
					    {name : 'Greenland',value:-1, number:-1},
					    {name : 'Guatemala',value:30, number:41	},			    
					    {name : 'French Guiana',value:-1, number:-1},
					    {name : 'Guyana',value:-1, number:-1},
					    {name : 'Honduras',value:55, number:34},
					    {name : 'Croatia',value:133, number:16},
					    {name : 'Haiti',value:28, number:42},
					    {name : 'Hungary',value:78, number:28},
					    {name : 'Indonesia',value:17, number:44},
					    {name : 'India',value:93, number:25},
					    {name : 'Ireland',value:5, number:57},				    
					    {name : 'Iran',value:-1, number:-1},
					    {name : 'Iraq',value:89, number:26},			
		                {name : 'Iceland',value:17, number:44},
		                {name : 'Israel',value:31, number:41},
		                {name : 'Italy',value:21, number:44},
		                {name : 'Jamaica',value:-1, number:-1},
		                {name : 'Jordan',value:-1, number:-1},
		                {name : 'Japan',value:-1, number:-1},
		                {name : 'Kazakhstan',value:66, number:31},
		                {name : 'Kenya',value:-1, number:-1},
		                {name : 'Kyrgyzstan',value:73, number:29},
		                {name : 'Cambodia',value:93, number:25},
		                {name : 'South Korea',value:-1, number:-1},
		                {name : 'Kosovo',value:78, number:29},     
		                {name : 'Kuwait',value:-1, number:-1},
		                {name : 'Laos',value:-1, number:-1},
		                {name : 'Lebanon',value:68, number:30},
		                {name : 'Liberia',value:-1, number:-1},
		                {name : 'Libya',value:-1, number:-1},
		                {name : 'Sri Lanka',value:10, number:48},	                
		                {name : 'Lesotho',value:-1, number:-1},
		                {name : 'Lithuania',value:120, number:19},
		                {name : 'Luxembourg',value:28, number:42},
		                {name : 'Latvia',value:93, number:25},
		                {name : 'Morocco',value:115, number:20},
		                {name : 'Moldova',value:88, number:27},
		                {name : 'Madagascar',value:113, number:21},
		                {name : 'Mexico',value:-1, number:-1},
		                {name : 'Macedonia',value:118, number:19},
		                {name : 'Mali',value:123, number:19},
		                {name : 'Myanmar',value:2, number:58},               
		                {name : 'Montenegro',value:126, number:18},
		                {name : 'Mongolia',value:41, number:39},
		                {name : 'Mozambique',value:-1, number:-1},
		                {name : 'Mauritania',value:93, number:25},
		                {name : 'Malawi',value:43, number:38},
		                {name : 'Malaysia',value:71, number:29},
		                {name : 'Namibia',value:-1, number:-1},
		                {name : 'New Caledonia',value:-1, number:-1},
		                {name : 'Niger',value:108, number:22},
		                {name : 'Nigeria',value:20, number:44},	                
		                {name : 'Nicaragua',value:82, number:27},
		                {name : 'Netherlands',value:8, number:54},	                
		                {name : 'Norway',value:11, number:48},
		                {name : 'Nepal',value:55, number:34},
		                {name : 'New Zealand',value:2, number:58},              
		                {name : 'Oman',value:-1, number:-1},
		                {name : 'Pakistan',value:53, number:35},
		                {name : 'Panama',value:48, number:36},
		                {name : 'Peru',value:74, number:29},
		                {name : 'Philippines',value:16, number:45},	                
		                {name : 'Papua New Guinea',value:-1, number:-1},
		                {name : 'Poland',value:84, number:27},
		                {name : 'Puerto Rico',value:-1, number:-1},
		                {name : 'North Korea',value:-1, number:-1},  
		                {name : 'Portugal',value:71, number:29},
		                {name : 'Paraguay',value:45, number:37},
		                {name : 'Qatar',value:9, number:51},	                
		                {name : 'Romania',value:105, number:23},
		                {name : 'Russia',value:-1, number:-1},
		                {name : 'Rwanda',value:128, number:17},
		                {name : 'Western Sahara',value:-1, number:-1},
		                {name : 'Saudi Arabia',value:57, number:33},
		                {name : 'Sudan',value:61, number:33},
		                {name : 'South Sudan',value:-1, number:-1},
		                {name : 'Senegal',value:57, number:33},              
		                {name : 'Solomon Islands',value:-1, number:-1},
		                {name : 'Sierra Leone',value:-1, number:-1},
		                {name : 'El Salvador',value:107, number:22},
		                {name : 'Somaliland',value:26, number:42},
		                {name : 'Somalia',value:-1, number:-1},
		                {name : 'Republic of Serbia',value:123, number:19},
		                {name : 'Suriname',value:66, number:31},    
		                {name : 'Slovakia',value:101, number:25},
		                {name : 'Slovenia',value:44, number:38},
		                {name : 'Sweden',value:39, number:39},
		                {name : 'Swaziland',value:-1, number:-1},
		                {name : 'Syria',value:35, number:40},	                
		                {name : 'Chad',value:93, number:25},
		                {name : 'Togo',value:-1, number:-1},
		                {name : 'Thailand',value:38, number:40},
		                {name : 'Tajikistan',value:64, number:32},
		                {name : 'Turkmenistan',value:26, number:42},	                
		                {name : 'East Timor',value:-1, number:-1},
		                {name : 'Trinidad and Tobago',value:-1, number:-1},
		                {name : 'Tunisia',value:103, number:23},
		                {name : 'Turkey',value:128, number:17},
		                {name : 'United Republic of Tanzania',value:51, number:36},
		                {name : 'Uganda',value:48, number:36},
		                {name : 'Ukraine',value:102, number:24},
		                {name : 'Uruguay',value:47, number:37},
		                {name : 'United States of America',value:1, number:61},              
		                {name : 'Uzbekistan',value:50, number:36},
		                {name : 'Venezuela',value:91, number:26},
		                {name : 'Vietnam',value:116, number:20},
		                {name : 'Vanuatu',value:-1, number:-1},
		                {name : 'West Bank',value:-1, number:-1},
		                {name : 'Yemen',value:130, number:17},
		                {name : 'South Africa',value:69, number:30},
		                {name : 'Zambia',value:45, number:37},
		                {name : 'Zimbabwe',value:82, number:27}
		            ],
		            [ //帮助陌生人指数
						{name : 'Afghanistan', value:62,number:33},	
						{name : 'Angola', value:-1,number:-1},
						{name : 'Albania', value:25,number:102},
						{name : 'United Arab Emirates', value:-1,number:-1},
						{name : 'Argentina', value:46,number:84},
						{name : 'Armenia', value:47,number:129},
						{name : 'French Southern and Antarctic Lands', value:-1,number:-1},
						{name : 'Australia', value:64,number:8},
						{name : 'Austria', value:-1,number:-1},
						{name : 'Azerbaijan', value:44,number:87},
						{name : 'Burundi', value:-1,number:-1},
						{name : 'Belgium', value:39,number:43},
						{name : 'Benin', value:37,number:122},
						{name : 'Burkina Faso', value:46,number:115},
						{name : 'Bangladesh', value:49,number:87},
						{name : 'Bulgaria', value:36,number:96},
						{name : 'The Bahamas', value:-1,number:-1},
						{name : 'Bosnia and Herzegovina', value:-1,number:-1},
						{name : 'Belarus', value:34,number:110},
						{name : 'Belize', value:-1,number:-1},
						{name : 'Bermuda', value:-1,number:-1},
						{name : 'Bolivia', value:54,number:65},
						{name : 'Brazil', value:42,number:72},
						{name : 'Brunei', value:-1,number:-1},
						{name : 'Bhutan', value:-1,number:-1},
						{name : 'Botswana', value:51,number:110},
						{name : 'Central African Republic', value:-1,number:-1},
						{name : 'Canada', value:64,number:7},
						{name : 'Switzerland', value:54,number:15},
						{name : 'Chile', value:53,number:18},
						{name : 'China', value:33,number:115},
						{name : 'Ivory Coast', value:-1,number:-1},
						{name : 'Cameroon', value:77,number:1},
						{name : 'Democratic Republic of the Congo', value:-1,number:-1},
						{name : 'Republic of the Congo', value:-1,number:-1},
						{name : 'Colombia', value:70,number:54},
						{name : 'Costa Rica', value:65,number:41},
						{name : 'Cuba', value:-1,number:-1},
						{name : 'Northern Cyprus', value:-1,number:-1},
						{name : 'Cyprus', value:54,number:27},
						{name : 'Czech Republic', value:34,number:75},
						{name : 'Germany', value:56,number:27},
						{name : 'Djibouti', value:-1,number:-1},
						{name : 'Denmark', value:53,number:18},
						{name : 'Dominican Republic', value:58,number:70},
						{name : 'Algeria', value:44,number:108},
						{name : 'Ecuador', value:45,number:80},
						{name : 'Egypt', value:47,number:96},
						{name : 'Eritrea', value:-1,number:-1},
						{name : 'Spain', value:50,number:47},
						{name : 'Estonia', value:77,number:1},
						{name : 'Ethiopia', value:43,number:115},
						{name : 'Finland', value:55,number:37},	
						{name : 'Fiji', value:-1,number:-1},
						{name : 'Falkland Islands', value:-1,number:-1},
						{name : 'France', value:35,number:70},
						{name : 'Gabon', value:59,number:108},
						{name : 'United Kingdom',value:65,number:2},
						{name : 'Georgia', value:38,number:135},
						{name : 'Ghana', value:50,number:60},
						{name : 'Guinea', value:51,number:87},
						{name : 'Gambia', value:-1,number:-1},
						{name : 'Guinea Bissau', value:-1,number:-1},
						{name : 'Equatorial Guinea', value:-1,number:-1},
						{name : 'Greece', value:30,number:130},
						{name : 'Greenland', value:-1,number:-1},
						{name : 'Guatemala', value:55,number:54},
						{name : 'French Guiana', value:-1,number:-1},
						{name : 'Guyana', value:-1,number:-1},
						{name : 'Honduras', value:50,number:72},
						{name : 'Croatia', value:31,number:115},
						{name : 'Haiti', value:44,number:30},
						{name : 'Hungary', value:52,number:80},
						{name : 'Indonesia', value:40,number:10},
						{name : 'India',value:29,number:58},
						{name : 'Ireland',value:64,number:4},
						{name : 'Iran', value:-1,number:-1},
						{name : 'Iraq', value:42,number:72},			
						{name : 'Iceland', value:45,number:10},
						{name : 'Israel', value:49,number:20},
						{name : 'Italy', value:56,number:24},
						{name : 'Jamaica', value:-1,number:-1},
						{name : 'Jordan', value:-1,number:-1},
						{name : 'Japan', value:-1,number:-1},
						{name : 'Kazakhstan', value:48,number:87},         
						{name : 'Kenya', value:-1,number:-1},              
						{name : 'Kyrgyzstan', value:47,number:96},             
						{name : 'Cambodia', value:21,number:30},           
						{name : 'South Korea', value:-1,number:-1},          
						{name : 'Kosovo', value:47,number:96},    
						{name : 'Kuwait', value:-1,number:-1},        
						{name : 'Laos', value:-1,number:-1},             
						{name : 'Lebanon', value:50,number:47},            
						{name : 'Liberia', value:-1,number:-1},              
						{name : 'Libya', value:-1,number:-1},            
						{name : 'Sri Lanka', value:54,number:30},        
						{name : 'Lesotho', value:-1,number:-1},        
						{name : 'Lithuania', value:37,number:122},     
						{name : 'Luxembourg', value:44,number:23},     
						{name : 'Latvia', value:35,number:50},               
						{name : 'Morocco', value:47,number:130},              
						{name : 'Moldova', value:39,number:75},               
						{name : 'Madagascar', value:25,number:115},               
						{name : 'Mexico', value:-1,number:-1},               
						{name : 'Macedonia', value:29,number:75},                
						{name : 'Mali', value:42,number:122},               
						{name : 'Myanmar',value:46,number:1},            
						{name : 'Montenegro', value:34,number:102},         
						{name : 'Mongolia', value:48,number:37},              
						{name : 'Mauritania', value:42,number:80},            
						{name : 'Malawi', value:56,number:54},             
						{name : 'Malaysia', value:33,number:42},          
						{name : 'Namibia', value:-1,number:-1},            
						{name : 'New Caledonia', value:-1,number:-1},     
						{name : 'Niger', value:49,number:130},     
						{name : 'Nigeria', value:66,number:52},   
						{name : 'Nicaragua', value:40,number:65},                
						{name : 'Netherlands',value:57,number:6},             
						{name : 'Norway', value:53,number:15},             
						{name : 'Nepal', value:50,number:65},               
						{name : 'New Zealand', value:67,number:8},              
						{name : 'Oman', value:-1,number:-1},              
						{name : 'Pakistan', value:51,number:40},             
						{name : 'Panama', value:44,number:45},               
						{name : 'Peru', value:45,number:80},               
						{name : 'Philippines', value:60,number:50},       
						{name : 'Papua New Guinea', value:-1,number:-1},     
						{name : 'Poland', value:37,number:47},          
						{name : 'Puerto Rico', value:-1,number:-1},   
						{name : 'North Korea', value:-1,number:-1},  
						{name : 'Portugal', value:45,number:60},           
						{name : 'Paraguay', value:39,number:25},           
						{name : 'Qatar', value:73,number:14},               
						{name : 'Romania', value:38,number:72},              
						{name : 'Russia', value:-1,number:-1},             
						{name : 'Rwanda', value:27,number:96},
						{name : 'Western Sahara', value:-1,number:-1},            
						{name : 'Saudi Arabia', value:58,number:60},              
						{name : 'Sudan', value:63,number:93},              
						{name : 'South Sudan', value:-1,number:-1},         
						{name : 'Senegal', value:68,number:93},      
						{name : 'Solomon Islands', value:-1,number:-1},         
						{name : 'Sierra Leone', value:-1,number:-1},       
						{name : 'El Salvador', value:38,number:110},    
						{name : 'Somaliland', value:59,number:25},                
						{name : 'Somalia', value:-1,number:-1},               
						{name : 'Republic of Serbia', value:31,number:86},             
						{name : 'Suriname', value:47,number:65},               
						{name : 'Slovakia', value:30,number:46},
						{name : 'Slovenia', value:45,number:43},             
						{name : 'Sweden', value:51,number:20},              
						{name : 'Swaziland', value:-1,number:-1},               
						{name : 'Syria', value:65,number:35},               
						{name : 'Chad', value:50,number:102},                
						{name : 'Togo', value:-1,number:-1},                
						{name : 'Thailand', value:37,number:4},               
						{name : 'Tajikistan', value:44,number:110},              
						{name : 'Turkmenistan', value:53,number:92},               
						{name : 'East Timor', value:-1,number:-1},              
						{name : 'Trinidad and Tobago', value:-1,number:-1},     
						{name : 'Tunisia', value:55,number:110},           
						{name : 'Turkey', value:34,number:102},          
						{name : 'United Republic of Tanzania', value:49,number:37},           
						{name : 'Uganda', value:61,number:65},             
						{name : 'Ukraine', value:36,number:122},           
						{name : 'Uruguay', value:55,number:35},            
						{name : 'United States of America', value:77,number:13},      
						{name : 'Uzbekistan', value:50,number:84},                
						{name : 'Venezuela', value:45,number:100},                
						{name : 'Vietnam', value:38,number:102},             
						{name : 'Vanuatu', value:-1,number:-1},          
						{name : 'West Bank', value:-1,number:-1},               
						{name : 'Yemen', value:41,number:134},             
						{name : 'South Africa', value:54,number:100},            
						{name : 'Zambia', value:63,number:75},            
						{name : 'Zimbabwe', value:49,number:115}
		       		],
			        [ // 资金援助指数
			            {name : 'Afghanistan',value:75,number:17},
					    {name : 'Angola',value:-1,number:-1},
					    {name : 'Albania',value:107,number:10},
					    {name : 'United Arab Emirates',value:-1,number:-1},
					    {name : 'Argentina',value:75,number:17},
					    {name : 'Armenia',value:113,number:8},
					    {name : 'French Southern and Antarctic Lands',value:-1,number:-1},
					    {name : 'Australia',value:18,number:34},
					    {name : 'Austria',value:-1,number:-1},
					    {name : 'Azerbaijan',value:30,number:28},
					    {name : 'Burundi',value:-1,number:-1},
					    {name : 'Belgium',value:41,number:25},
					    {name : 'Benin',value:95,number:12},
					    {name : 'Burkina Faso',value:113,number:8},
					    {name : 'Bangladesh',value:90,number:13},
					    {name : 'Bulgaria',value:121,number:7},
					    {name : 'The Bahamas',value:-1,number:-1},
					    {name : 'Bosnia and Herzegovina',value:-1,number:-1},
					    {name : 'Belarus',value:22,number:30},
					    {name : 'Belize',value:-1,number:-1},
					    {name : 'Bermuda',value:-1,number:-1},
					    {name : 'Bolivia',value:47,number:24},
					    {name : 'Brazil',value:90,number:13},
					    {name : 'Brunei',value:-1,number:-1},
					    {name : 'Bhutan',value:-1,number:-1},
					    {name : 'Botswana',value:60,number:19},
					    {name : 'Central African Republic',value:-1,number:-1},
					    {name : 'Canada',value:6,number:42},
					    {name : 'Switzerland',value:20,number:32},
					    {name : 'Chile',value:90,number:13},
					    {name : 'China',value:131,number:4},
					    {name : 'Ivory Coast',value:-1,number:-1},
					    {name : 'Cameroon',value:1,number:35},
					    {name : 'Democratic Republic of the Congo',value:-1,number:-1},
					    {name : 'Republic of the Congo',value:-1,number:-1},
					    {name : 'Colombia',value:47,number:24},
					    {name : 'Costa Rica',value:34,number:27},
					    {name : 'Cuba',value:-1,number:-1},
					    {name : 'Northern Cyprus',value:-1,number:-1},
					    {name : 'Cyprus',value:34,number:27},
					    {name : 'Czech Republic',value:88,number:14},
					    {name : 'Germany',value:34,number:27},
					    {name : 'Djibouti',value:-1,number:-1},
					    {name : 'Denmark',value:57,number:20},
					    {name : 'Dominican Republic',value:16,number:35},
					    {name : 'Algeria',value:113,number:8},
					    {name : 'Ecuador',value:82,number:15},
					    {name : 'Egypt',value:121,number:7},
					    {name : 'Eritrea',value:-1,number:-1},
					    {name : 'Spain',value:1,number:35},
					    {name : 'Estonia',value:75,number:17},
					    {name : 'Ethiopia',value:102,number:11},
					    {name : 'Finland',value:34,number:27},
					    {name : 'Fiji',value:-1,number:-1},
					    {name : 'Falkland Islands',value:-1,number:-1},
					    {name : 'France',value:41,number:25},
					    {name : 'Gabon',value:95,number:12},
					    {name : 'United Kingdom',value:26,number:29},
					    {name : 'Georgia',value:68,number:18},
					    {name : 'Ghana',value:54,number:21},
					    {name : 'Guinea',value:68,number:18},
					    {name : 'Gambia',value:-1,number:-1},
					    {name : 'Guinea Bissau',value:-1,number:-1},
					    {name : 'Equatorial Guinea',value:-1,number:-1},
					    {name : 'Greece',value:131,number:4},
					    {name : 'Greenland',value:-1,number:-1},
					    {name : 'Guatemala',value:8,number:40},
					    {name : 'French Guiana',value:-1,number:-1},
					    {name : 'Guyana',value:-1,number:-1},
					    {name : 'Honduras',value:30,number:28},
					    {name : 'Croatia',value:127,number:6},
					    {name : 'Haiti',value:14,number:36},
					    {name : 'Hungary',value:107,number:10},
					    {name : 'Indonesia',value:22,number:30},
					    {name : 'India',value:68,number:18},
					    {name : 'Ireland',value:11,number:37},
					    {name : 'Iran',value:-1,number:-1},
					    {name : 'Iraq',value:90,number:13},				
			            {name : 'Iceland',value:41,number:25},
			            {name : 'Israel',value:54,number:21},
			            {name : 'Italy',value:41,number:25},
			            {name : 'Jamaica',value:-1,number:-1},
			            {name : 'Jordan',value:-1,number:-1},
			            {name : 'Japan',value:-1,number:-1},
			            {name : 'Kazakhstan',value:26,number:29},
			            {name : 'Kenya',value:-1,number:-1},
			            {name : 'Kyrgyzstan',value:41,number:25},
			            {name : 'Cambodia',value:111,number:9},
			            {name : 'South Korea',value:-1,number:-1},
			            {name : 'Kosovo',value:41,number:25},     
			            {name : 'Kuwait',value:-1,number:-1},
			            {name : 'Laos',value:-1,number:-1},
			            {name : 'Lebanon',value:113,number:8},
			            {name : 'Liberia',value:-1,number:-1},
			            {name : 'Libya',value:-1,number:-1},
			            {name : 'Sri Lanka',value:2,number:26},
			            {name : 'Lesotho',value:-1,number:-1},
			            {name : 'Lithuania',value:95,number:12},
			            {name : 'Luxembourg',value:22,number:30},
			            {name : 'Latvia',value:111,number:9},
			            {name : 'Morocco',value:121,number:7},
			            {name : 'Moldova',value:60,number:19},
			            {name : 'Madagascar',value:34,number:27},
			            {name : 'Mexico',value:-1,number:-1},
			            {name : 'Macedonia',value:121,number:7},
			            {name : 'Mali',value:127,number:6},
			            {name : 'Myanmar',value:4,number:43},
			            {name : 'Montenegro',value:113,number:8},
			            {name : 'Mongolia',value:26,number:29},
			            {name : 'Mozambique',value:-1,number:-1},
			            {name : 'Mauritania',value:95,number:12},
			            {name : 'Malawi',value:22,number:30},
			            {name : 'Malaysia',value:60,number:19},
			            {name : 'Namibia',value:-1,number:-1},
			            {name : 'New Caledonia',value:-1,number:-1},
			            {name : 'Niger',value:102,number:11},
			            {name : 'Nigeria',value:14,number:36},
			            {name : 'Nicaragua',value:75,number:17},
			            {name : 'Netherlands',value:11,number:37},
			            {name : 'Norway',value:16,number:35},
			            {name : 'Nepal',value:40,number:26},
			            {name : 'New Zealand',value:8,number:40},
			            {name : 'Oman',value:-1,number:-1},
			            {name : 'Pakistan',value:82,number:15},
			            {name : 'Panama',value:21,number:31},
			            {name : 'Peru',value:57,number:20},
			            {name : 'Philippines',value:4,number:43},
			            {name : 'Papua New Guinea',value:-1,number:-1},
			            {name : 'Poland',value:95,number:12},
			            {name : 'Puerto Rico',value:-1,number:-1},
			            {name : 'North Korea',value:-1,number:-1},   
			            {name : 'Portugal',value:81,number:16},
			            {name : 'Paraguay',value:47,number:24},
			            {name : 'Qatar',value:60,number:19},
			            {name : 'Romania',value:113,number:8},
			            {name : 'Russia',value:-1,number:-1},
			            {name : 'Rwanda',value:107,number:10},
			            {name : 'Western Sahara',value:-1,number:-1},
			            {name : 'Saudi Arabia',value:88,number:14},
			            {name : 'Sudan',value:60,number:19},
			            {name : 'South Sudan',value:-1,number:-1},
			            {name : 'Senegal',value:82,number:15},
			            {name : 'Solomon Islands',value:-1,number:-1},
			            {name : 'Sierra Leone',value:-1,number:-1},
			            {name : 'El Salvador',value:68,number:18},
			            {name : 'Somaliland',value:68,number:18},
			            {name : 'Somalia',value:-1,number:-1},
			            {name : 'Republic of Serbia',value:121,number:7},
			            {name : 'Suriname',value:53,number:22},                
			            {name : 'Slovakia',value:102,number:11},
			            {name : 'Slovenia',value:18,number:34},
			            {name : 'Sweden',value:90,number:13},
			            {name : 'Swaziland',value:-1,number:-1},
			            {name : 'Syria',value:82,number:15},
			            {name : 'Chad',value:95,number:12},
			            {name : 'Togo',value:-1,number:-1},
			            {name : 'Thailand',value:95,number:12},
			            {name : 'Tajikistan',value:7,number:41},
			            {name : 'Turkmenistan',value:1,number:57},
			            {name : 'East Timor',value:-1,number:-1},
			            {name : 'Trinidad and Tobago',value:-1,number:-1},
			            {name : 'Tunisia',value:131,number:4},
			            {name : 'Turkey',value:130,number:5},
			            {name : 'United Republic of Tanzania',value:60,number:19},
			            {name : 'Uganda',value:51,number:23},
			            {name : 'Ukraine',value:26,number:29},
			            {name : 'Uruguay',value:82,number:15},
			            {name : 'United States of America',value:3,number:45},
			            {name : 'Uzbekistan',value:10,number:38},
			            {name : 'Venezuela',value:60,number:19},
			            {name : 'Vietnam',value:113,number:8},
			            {name : 'Vanuatu',value:-1,number:-1},
			            {name : 'West Bank',value:-1,number:-1},                
			            {name : 'Yemen',value:131,number:4},
			            {name : 'South Africa',value:54,number:21},
			            {name : 'Zambia',value:34,number:27},
			            {name : 'Zimbabwe',value:51,number:23}
			        ],
			        [//志愿服务指数
						{name : 'Afghanistan',value:35, number:40},
						{name : 'Angola',value:-1, number:-1},
						{name : 'Albania',value:107, number:10},
						{name : 'United Arab Emirates',value:-1, number:-1},
						{name : 'Argentina',value:75, number:17},
						{name : 'Armenia',value:113, number:8},
						{name : 'French Southern and Antarctic Lands',value:-1, number:-1},
						{name : 'Australia',value:18, number:34},
						{name : 'Austria',value:-1, number:-1},
						{name : 'Azerbaijan',value:30, number:28},
						{name : 'Burundi',value:-1, number:-1},
						{name : 'Belgium',value:41, number:25},
						{name : 'Benin',value:95, number:12},
						{name : 'Burkina Faso',value:113, number:8},
						{name : 'Bangladesh',value:90, number:13},
						{name : 'Bulgaria',value:90, number:13},
						{name : 'The Bahamas',value:-1, number:-1},
						{name : 'Bosnia and Herzegovina',value:-1, number:-1},
						{name : 'Belarus',value:22, number:30},
						{name : 'Belize',value:-1, number:-1},
						{name : 'Bermuda',value:-1, number:-1},
						{name : 'Bolivia',value:47, number:24},
						{name : 'Brazil',value:90, number:13},
						{name : 'Brunei',value:-1, number:-1},
						{name : 'Bhutan',value:-1, number:-1},
						{name : 'Botswana',value:60, number:19},
						{name : 'Central African Republic',value:-1, number:-1},
						{name : 'Canada',value:6, number:42},			    
						{name : 'Switzerland',value:20, number:32},
						{name : 'Chile',value:90, number:13},
						{name : 'China',value:131, number:4},
						{name : 'Ivory Coast',value:-1, number:-1},
						{name : 'Cameroon',value:90, number:13},
						{name : 'Democratic Republic of the Congo',value:-1, number:-1},
						{name : 'Republic of the Congo',value:-1, number:-1},
						{name : 'Colombia',value:47, number:24},
						{name : 'Costa Rica',value:34, number:27},
						{name : 'Cuba',value:-1, number:-1},
						{name : 'Northern Cyprus',value:-1, number:-1},
						{name : 'Cyprus',value:34, number:27},
						{name : 'Czech Republic',value:88, number:14},
						{name : 'Germany',value:34, number:27},
						{name : 'Djibouti',value:-1, number:-1},
						{name : 'Denmark',value:57, number:20},
						{name : 'Dominican Republic',value:16, number:35},
						{name : 'Algeria',value:113, number:8},
						{name : 'Ecuador',value:82, number:15},
						{name : 'Egypt',value:121, number:7},
						{name : 'Eritrea',value:-1, number:-1},
						{name : 'Spain',value:75, number:17},				    
						{name : 'Estonia',value:68, number:18},			    
						{name : 'Ethiopia',value:102, number:11},
						{name : 'Finland',value:34, number:27},
						{name : 'Fiji',value:-1, number:-1},
						{name : 'Falkland Islands',value:-1, number:-1},
						{name : 'France',value:41, number:25},
						{name : 'Gabon',value:95, number:12},
						{name : 'United Kingdom',value:26, number:29},		    
						{name : 'Georgia',value:68, number:18},
						{name : 'Ghana',value:54, number:21},
						{name : 'Guinea',value:68, number:18},
						{name : 'Gambia',value:-1, number:-1},
						{name : 'Guinea Bissau',value:-1, number:-1},
						{name : 'Equatorial Guinea',value:-1, number:-1},
						{name : 'Greece',value:131, number:4},
						{name : 'Greenland',value:-1, number:-1},
						{name : 'Guatemala',value:8, number:40},			    
						{name : 'French Guiana',value:-1, number:-1},
						{name : 'Guyana',value:-1, number:-1},
						{name : 'Honduras',value:30, number:28},
						{name : 'Croatia',value:127, number:6},
						{name : 'Haiti',value:14, number:36},
						{name : 'Hungary',value:107, number:10},
						{name : 'Indonesia',value:22, number:30},
						{name : 'India',value:68, number:18},
						{name : 'Ireland',value:11, number:37},				    
						{name : 'Iran',value:-1, number:-1},
						{name : 'Iraq',value:102, number:11},			
						{name : 'Iceland',value:41, number:25},
						{name : 'Israel',value:54, number:21},
						{name : 'Italy',value:41, number:25},
						{name : 'Jamaica',value:-1, number:-1},
						{name : 'Jordan',value:-1, number:-1},
						{name : 'Japan',value:-1, number:-1},
						{name : 'Kazakhstan',value:26, number:29},
						{name : 'Kenya',value:-1, number:-1},
						{name : 'Kyrgyzstan',value:41, number:25},
						{name : 'Cambodia',value:111, number:9},
						{name : 'South Korea',value:-1, number:-1},
						{name : 'Kosovo',value:113, number:8},     
						{name : 'Kuwait',value:-1, number:-1},
						{name : 'Laos',value:-1, number:-1},
						{name : 'Lebanon',value:113, number:8},
						{name : 'Liberia',value:-1, number:-1},
						{name : 'Libya',value:-1, number:-1},
						{name : 'Sri Lanka',value:2, number:46},	                
						{name : 'Lesotho',value:-1, number:-1},
						{name : 'Lithuania',value:95, number:12},
						{name : 'Luxembourg',value:22, number:30},
						{name : 'Latvia',value:111, number:9},
						{name : 'Morocco',value:121, number:7},
						{name : 'Moldova',value:60, number:19},
						{name : 'Madagascar',value:34, number:27},
						{name : 'Mexico',value:-1, number:-1},
						{name : 'Macedonia',value:121, number:7},
						{name : 'Mali',value:127, number:6},
						{name : 'Myanmar',value:4, number:43},               
						{name : 'Montenegro',value:113, number:8},
						{name : 'Mongolia',value:26, number:29},
						{name : 'Mozambique',value:-1, number:-1},
						{name : 'Mauritania',value:95, number:12},
						{name : 'Malawi',value:22, number:30},
						{name : 'Malaysia',value:60, number:19},
						{name : 'Namibia',value:-1, number:-1},
						{name : 'New Caledonia',value:-1, number:-1},
						{name : 'Niger',value:102, number:11},
						{name : 'Nigeria',value:14, number:36},	                
						{name : 'Nicaragua',value:75, number:17},
						{name : 'Netherlands',value:11, number:37},	                
						{name : 'Norway',value:16, number:35},
						{name : 'Nepal',value:40, number:26},
						{name : 'New Zealand',value:8, number:40},              
						{name : 'Oman',value:-1, number:-1},
						{name : 'Pakistan',value:82, number:15},
						{name : 'Panama',value:21, number:31},
						{name : 'Peru',value:57, number:20},
						{name : 'Philippines',value:4, number:43},	                
						{name : 'Papua New Guinea',value:-1, number:-1},
						{name : 'Poland',value:95, number:12},
						{name : 'Puerto Rico',value:-1, number:-1},
						{name : 'North Korea',value:-1, number:-1},  
						{name : 'Portugal',value:81, number:16},
						{name : 'Paraguay',value:47, number:24},
						{name : 'Qatar',value:60, number:19},	                
						{name : 'Romania',value:113, number:8},
						{name : 'Russia',value:-1, number:-1},
						{name : 'Rwanda',value:107, number:10},
						{name : 'Western Sahara',value:-1, number:-1},
						{name : 'Saudi Arabia',value:88, number:14},
						{name : 'Sudan',value:60, number:19},
						{name : 'South Sudan',value:-1, number:-1},
						{name : 'Senegal',value:82, number:15},              
						{name : 'Solomon Islands',value:-1, number:-1},
						{name : 'Sierra Leone',value:-1, number:-1},
						{name : 'El Salvador',value:68, number:18},
						{name : 'Somaliland',value:68, number:18},
						{name : 'Somalia',value:-1, number:-1},
						{name : 'Republic of Serbia',value:-1, number:-1},
						{name : 'Suriname',value:53, number:22},    
						{name : 'Slovakia',value:102, number:11},
						{name : 'Slovenia',value:18, number:34},
						{name : 'Sweden',value:90, number:19},
						{name : 'Swaziland',value:-1, number:-1},
						{name : 'Syria',value:82, number:15},	                
						{name : 'Chad',value:95, number:12},
						{name : 'Togo',value:-1, number:-1},
						{name : 'Thailand',value:95, number:12},
						{name : 'Tajikistan',value:7, number:41},
						{name : 'Turkmenistan',value:1, number:57},	                
						{name : 'East Timor',value:-1, number:-1},
						{name : 'Trinidad and Tobago',value:-1, number:-1},
						{name : 'Tunisia',value:131, number:4},
						{name : 'Turkey',value:130, number:5},
						{name : 'United Republic of Tanzania',value:-1, number:-1},
						{name : 'Uganda',value:51, number:23},
						{name : 'Ukraine',value:26, number:29},
						{name : 'Uruguay',value:82, number:15},
						{name : 'United States of America',value:3, number:35},              
						{name : 'Uzbekistan',value:10, number:38},
						{name : 'Venezuela',value:60, number:19},
						{name : 'Vietnam',value:113, number:8},
						{name : 'Vanuatu',value:-1, number:-1},
						{name : 'West Bank',value:-1, number:-1},
						{name : 'Yemen',value:131, number:4},
						{name : 'South Africa',value:54, number:21},
						{name : 'Zambia',value:34, number:27},
						{name : 'Zimbabwe',value:51, number:23}
					]
				]
        	]
        ],
        nameMap:{
            'Afghanistan':'阿富汗',
            'Angola':'安哥拉',
            'Albania':'阿尔巴尼亚',
            'United Arab Emirates':'阿联酋',
            'Argentina':'阿根廷',
            'Armenia':'亚美尼亚',
            'French Southern and Antarctic Lands':'法属南半球和南极领地',
            'Australia':'澳大利亚',
            'Austria':'奥地利',
            'Azerbaijan':'阿塞拜疆',
            'Burundi':'布隆迪',
            'Belgium':'比利时',
            'Benin':'贝宁',
            'Burkina Faso':'布基纳法索',
            'Bangladesh':'孟加拉国',
            'Bulgaria':'保加利亚',
            'The Bahamas':'巴哈马',
            'Bosnia and Herzegovina':'波斯尼亚和黑塞哥维那',
            'Belarus':'白俄罗斯',
            'Belize':'伯利兹',
            'Bermuda':'百慕大',
            'Bolivia':'玻利维亚',
            'Brazil':'巴西',
            'Brunei':'文莱',
            'Bhutan':'不丹',
            'Botswana':'博茨瓦纳',
            'Central African Republic':'中非共和国',
            'Canada':'加拿大',
            'Switzerland':'瑞士',
            'Chile':'智利',
            'China':'中国',
            'Ivory Coast':'象牙海岸',
            'Cameroon':'喀麦隆',
            'Democratic Republic of the Congo':'刚果民主共和国',
            'Republic of the Congo':'刚果共和国',
            'Colombia':'哥伦比亚',
            'Costa Rica':'哥斯达黎加',
            'Cuba':'古巴',
            'Northern Cyprus':'北塞浦路斯',
            'Cyprus':'塞浦路斯',
            'Czech Republic':'捷克共和国',
            'Germany':'德国',
            'Djibouti':'吉布提',
            'Denmark':'丹麦',
            'Dominican Republic':'多明尼加共和国',
            'Algeria':'阿尔及利亚',
            'Ecuador':'厄瓜多尔',
            'Egypt':'埃及',
            'Eritrea':'厄立特里亚',
            'Spain':'西班牙',
            'Estonia':'爱沙尼亚',
            'Ethiopia':'埃塞俄比亚',
            'Finland':'芬兰',
            'Fiji':'斐',
            'Falkland Islands':'福克兰群岛',
            'France':'法国',
            'Gabon':'加蓬',
            'United Kingdom':'英国',
            'Georgia':'格鲁吉亚',
            'Ghana':'加纳',
            'Guinea':'几内亚',
            'Gambia':'冈比亚',
            'Guinea Bissau':'几内亚比绍',
            'Equatorial Guinea':'赤道几内亚',
            'Greece':'希腊',
            'Greenland':'格陵兰',
            'Guatemala':'危地马拉',
            'French Guiana':'法属圭亚那',
            'Guyana':'圭亚那',
            'Honduras':'洪都拉斯',
            'Croatia':'克罗地亚',
            'Haiti':'海地',
            'Hungary':'匈牙利',
            'Indonesia':'印尼',
            'India':'印度',
            'Ireland':'爱尔兰',
            'Iran':'伊朗',
            'Iraq':'伊拉克',
            'Iceland':'冰岛',
            'Israel':'以色列',
            'Italy':'意大利',
            'Jamaica':'牙买加',
            'Jordan':'约旦',
            'Japan':'日本',
            'Kazakhstan':'哈萨克斯坦',
            'Kenya':'肯尼亚',
            'Kyrgyzstan':'吉尔吉斯斯坦',
            'Cambodia':'柬埔寨',
            'South Korea':'韩国',
            'Kosovo':'科索沃',
            'Kuwait':'科威特',
            'Laos':'老挝',
            'Lebanon':'黎巴嫩',
            'Liberia':'利比里亚',
            'Libya':'利比亚',
            'Sri Lanka':'斯里兰卡',
            'Lesotho':'莱索托',
            'Lithuania':'立陶宛',
            'Luxembourg':'卢森堡',
            'Latvia':'拉脱维亚',
            'Morocco':'摩洛哥',
            'Moldova':'摩尔多瓦',
            'Madagascar':'马达加斯加',
            'Mexico':'墨西哥',
            'Macedonia':'马其顿',
            'Mali':'马里',
            'Myanmar':'缅甸',
            'Montenegro':'黑山',
            'Mongolia':'蒙古',
            'Mozambique':'莫桑比克',
            'Mauritania':'毛里塔尼亚',
            'Malawi':'马拉维',
            'Malaysia':'马来西亚',
            'Namibia':'纳米比亚',
            'New Caledonia':'新喀里多尼亚',
            'Niger':'尼日尔',
            'Nigeria':'尼日利亚',
            'Nicaragua':'尼加拉瓜',
            'Netherlands':'荷兰',
            'Norway':'挪威',
            'Nepal':'尼泊尔',
            'New Zealand':'新西兰',
            'Oman':'阿曼',
            'Pakistan':'巴基斯坦',
            'Panama':'巴拿马',
            'Peru':'秘鲁',
            'Philippines':'菲律宾',
            'Papua New Guinea':'巴布亚新几内亚',
            'Poland':'波兰',
            'Puerto Rico':'波多黎各',
            'North Korea':'北朝鲜',
            'Portugal':'葡萄牙',
            'Paraguay':'巴拉圭',
            'Qatar':'卡塔尔',
            'Romania':'罗马尼亚',
            'Russia':'俄罗斯',
            'Rwanda':'卢旺达',
            'Western Sahara':'西撒哈拉',
            'Saudi Arabia':'沙特阿拉伯',
            'Sudan':'苏丹',
            'South Sudan':'南苏丹',
            'Senegal':'塞内加尔',
            'Solomon Islands':'所罗门群岛',
            'Sierra Leone':'塞拉利昂',
            'El Salvador':'萨尔瓦多',
            'Somaliland':'索马里兰',
            'Somalia':'索马里',
            'Republic of Serbia':'塞尔维亚共和国',
            'Suriname':'苏里南',
            'Slovakia':'斯洛伐克',
            'Slovenia':'斯洛文尼亚',
            'Sweden':'瑞典',
            'Swaziland':'斯威士兰',
            'Syria':'叙利亚',
            'Chad':'乍得',
            'Togo':'多哥',
            'Thailand':'泰国',
            'Tajikistan':'塔吉克斯坦',
            'Turkmenistan':'土库曼斯坦',
            'East Timor':'东帝汶',
            'Trinidad and Tobago':'特里尼达和多巴哥',
            'Tunisia':'突尼斯',
            'Turkey':'土耳其',
            'United Republic of Tanzania':'坦桑尼亚联合共和国',
            'Uganda':'乌干达',
            'Ukraine':'乌克兰',
            'Uruguay':'乌拉圭',
            'United States of America':'美国',
            'Uzbekistan':'乌兹别克斯坦',
            'Venezuela':'委内瑞拉',
            'Vietnam':'越南',
            'Vanuatu':'瓦努阿图',
            'West Bank':'西岸',
            'Yemen':'也门',
            'South Africa':'南非',
            'Zambia':'赞比亚',
            'Zimbabwe':'津巴布韦'
        }
    };
	window.getData = function( index ){
		// index 表示指数的类别
		var _index = index || 0;
		var res = {};
		res.data =_data.year[_index];
		res.nameMap = _data.nameMap;
        return res;
	};
})( window);